### ISSUE TITLE
Batch Dot and Reshape error

### ISSUE THREAD

**Issue by AKASH2907** [johnsmithm/multi-heads-attention-image-classification#4]
There's a batch dot error that shows at Line 34, axes given 4,3 that's out of range error. It should be 3,2 with the given arrays as [64, 8, 8] and [64, 8, 64].

After resolving tabove error, I am getting a Reshape error. Model summary prints fine. The error is :

```javascript
Traceback (most recent call last):
  File "multi-heads-attention-mnist.py", line 121, in <module>
    validation_data=(X_test, Y_test)
  File "/home/intern_akash/akash_hpc/lib/python3.6/site-packages/keras/engine/training.py", line 1239, in fit
    validation_freq=validation_freq)
  File "/home/intern_akash/akash_hpc/lib/python3.6/site-packages/keras/engine/training_arrays.py", line 196, in fit_loop
    outs = fit_function(ins_batch)
  File "/home/intern_akash/akash_hpc/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 3292, in __call__
    run_metadata=self.run_metadata)
  File "/home/intern_akash/akash_hpc/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1458, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Input to reshape is a tensor with 1146617856 values, but the requested shape has 884736
	 [[{{node model_1/reshape_5/Reshape}}]]
	 [[metrics/accuracy/Identity/_243]]
  (1) Invalid argument: Input to reshape is a tensor with 1146617856 values, but the requested shape has 884736
	 [[{{node model_1/reshape_5/Reshape}}]]
```

**Comment by zhengx18** [comment]
I have the same problem, have you ever solved this problem?

**Comment by eksis77** [comment]
refer this url,
https://medium.com/@mahimanzumhaquepantho/i-solved-the-dimention-issue-for-new-tf-version-and-uploaded-it-here-53875c4be837

**Comment by duanchao** [comment]
> There's a batch dot error that shows at Line 34, axes given 4,3 that's out of range error. It should be 3,2 with the given arrays as [64, 8, 8] and [64, 8, 64].
> 
> After resolving tabove error, I am getting a Reshape error. Model summary prints fine. The error is :
> 
> ```js
> Traceback (most recent call last):
>   File "multi-heads-attention-mnist.py", line 121, in <module>
>     validation_data=(X_test, Y_test)
>   File "/home/intern_akash/akash_hpc/lib/python3.6/site-packages/keras/engine/training.py", line 1239, in fit
>     validation_freq=validation_freq)
>   File "/home/intern_akash/akash_hpc/lib/python3.6/site-packages/keras/engine/training_arrays.py", line 196, in fit_loop
>     outs = fit_function(ins_batch)
>   File "/home/intern_akash/akash_hpc/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 3292, in __call__
>     run_metadata=self.run_metadata)
>   File "/home/intern_akash/akash_hpc/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1458, in __call__
>     run_metadata_ptr)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
>   (0) Invalid argument: Input to reshape is a tensor with 1146617856 values, but the requested shape has 884736
> 	 [[{{node model_1/reshape_5/Reshape}}]]
> 	 [[metrics/accuracy/Identity/_243]]
>   (1) Invalid argument: Input to reshape is a tensor with 1146617856 values, but the requested shape has 884736
> 	 [[{{node model_1/reshape_5/Reshape}}]]
> ```

hello ，did you solve this problem？

**Comment by duanchao** [comment]
did someone solve this problem？call me please  870266923@qq.com
